get_registrations_data:
  every: 10m
  class: GetRegistrationsDataJob
  queue: normal
get_movements_data:
  every: 1h
  class: GetMovementDataJob
  queue: high
  after_schedule: NormalizeMovementsDataJob
get_room_data:
  cron: "30 09 * * *"
  class: GetRoomsDataJob
  queue: daily
get_class_data:
  cron: "30 09 * * *"
  class: GetRoomClassDataJob
  queue: daily
get_bed:
  cron: "30 10 * * *"
  class: GetBedDataJob
  queue: daily
do_room_census:
  cron: "30 23 * * *"
  class: InpatientDayRoomCensusJob
  queue: daily
  description: This will run room census job every day at 23 30
do_hospital_census:
  cron: "30 23 * * *"
  class: InpatientDaysCensusJob
  queue: daily
  description: this will run hospital census job every day at 23 30