# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 05362a61488efde35d2c0282aef054638882d0c203299d7116cf475c6663b72876f09aa9fafaa19907748d9d6323317b838d8c529d534a5c4dc6efe2ce086490

test:
  secret_key_base: 35bde9297c8e4a218fdc387783c598f8cb416ce0d503765fbd46f74fc1a209241e2ea318812456be8468c3b673abbf6cd79ff7a95c85ed684d73a4a8ad40065c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
